BarkModelManager.py, clear_audio.py, config.py, create_base_filename.py, gen_tortoise.py, generation_tab_bark.py, get_date.py, history_tab.py, load_config.py, model_manager.py, models/.gitignore, models/clone.sh, save_waveform_plot.py, server.py, settings_tab.py, setup_or_recover.py
Added tortoise tts support and improved the code base to be able to scale better
=> Add Tortoise support, refactor code

.gitignore, README.md, server.py, src/history_tab/collections_directories_atom.py, src/history_tab/delete_generation_cb.py, src/history_tab/main.py, src/history_tab/save_to_favorites.py
=> Collections

server.py, src/bark/clone/tab_voice_clone_demo.py, src/bark/generate_and_save_metadata.py, src/bark/generation_tab_bark.py, src/bark/get_audio_from_npz.py, src/bark/get_bark_voice_hash.py, src/bark/history_to_hash.py, src/bark/npz_tools.py, src/extensions_loader/extensions/callback_save_generation_ffmpeg.py, src/history_tab/edit_metadata_ui.py, src/history_tab/main.py, src/history_tab/voices_tab.py
Fix a few bugs and improve metadata, also include it in the npz
=> Improve metadata

requirements.txt, server.py, src/vocos/vocos_tab_bark.py
=> vocos npz tab

server.py, src/bark/clone/tab_voice_clone_demo.py, src/bark/generate_and_save_metadata.py, src/bark/generation_tab_bark.py
add "use as voice" button, improve audio input now that ffmpeg is installed
=> fix and upgrade voice clone tab

server.py, src/vocos/vocos_tab_wav.py, src/vocos/vocos_tabs.py
=> add vocos wav tab

server.py, src/Joutai.py, src/bark/BarkModelManager.py, src/bark/generation_tab_bark.py, src/css/css.py, src/musicgen/musicgen_css.py, src/studio/studio_tab.css, src/studio/studio_tab.py, src/utils/load_css.py, src/utils/save_waveform_plot.py
* include fixes and prevent a breakdown if there's not enough VRAM on loading
=> Studio-tab

requirements.txt, server.py, src/bark/settings_tab_bark.py, src/config/save_config_bark.py, src/musicgen/musicgen_tab.py
=> Upgrade bark settings

README.md, models/.gitignore, models/clone.sh, requirements.txt, requirements_bark_hubert_quantizer.txt, server.py, src/bark/BarkModelManager.py, src/bark/clone/tab_voice_clone.py, src/bark/clone/tab_voice_clone_error.py, src/bark/create_voice_string.py, src/bark/generate_and_save_metadata.py, src/bark/generation_tab_bark.py, src/bark/get_audio_from_npz.py, src/extensions_loader/extensions/callback_save_generation_ffmpeg.py, src/musicgen/musicgen_tab.py
=> Improve installation, prepare for v5 installer

README.md, server.py, src/demucs/demucs_tab.py, src/demucs/demucs_tab_error.py, src/musicgen/musicgen_tab_error.py
=> add demucs

.gitignore, README.md, src/history_tab/open_folder.py, src/history_tab/voices_tab.py, src/tortoise/TortoiseParameters.py, src/tortoise/gen_tortoise.py, src/tortoise/generation_tab_tortoise.py, src/tortoise/gr_reload_button.py, src/utils/setup_or_recover.py
Relates to: https://github.com/rsxdalv/tts-generation-webui/issues/72
=> Tortoise model and voice selection improvements

README.md, src/history_tab/open_folder.py, src/rvc_tab/rvc_tab.py, src/tortoise/gen_tortoise.py, src/tortoise/generation_tab_tortoise.py, src/utils/get_path_from_root.py
=> Add RVC dropdowns

README.md, src/history_tab/save_photo.py, src/history_tab/voices_tab.py
Now it's possible to have a png file with the same name as a voice and to see this picture in the UI.
Also, if you upload a picture from the UI, it will be renamed to the matching filename.
=> Voice Photo Demo

README.md, requirements.txt, src/bark/FinalGenParams.py, src/bark/extended_generate.py, src/bark/generation_tab_bark.py
=> voice mixing, burn in prompt, generation length

README.md, react-ui/src/pages/musicgen.tsx
=> React musicgen

README.md, requirements.txt, server.py, src/bark/bark_css.py, src/bark/generation_tab_bark.py, src/extensions_loader/ext_callback_save_generation.py, src/history_tab/main.py, src/history_tab/voices_tab.py
Example of new console output:
```
Loading extensions:
Loaded extension: callback_save_generation_ffmpeg
Loaded extension: callback_save_generation_musicgen_ffmpeg
Loaded extension: empty_extension
Loaded 2 callback_save_generation extensions.
Loaded 1 callback_save_generation_musicgen extensions.    
Starting Gradio server...
Gradio interface options:     
inline:               False  
inbrowser:            True   
share:                False  
debug:                False  
max_threads:          40     
auth:                 None   
auth_message:         None   
prevent_thread_lock:  False  
show_error:           True   
server_name:          0.0.0.0
server_port:          7860   
show_tips:            False  
height:               500    
width:                100%   
favicon_path: …
```
=> Fixing errors and upgrading gradio

README.md, notebooks/google_collab.ipynb, src/extensions_loader/extensions/callback_save_generation_ffmpeg_flac.py, src/extensions_loader/extensions/callback_save_generation_musicgen_ffmpeg_flac.py, src/musicgen/musicgen_tab.py
Fixes https://github.com/rsxdalv/tts-generation-webui/issues/275
Also fix Node.js install in Colab.
=> Fix MusicGen Stereo MultiBandDiffusion

Dockerfile, README.md, notebooks/styleTTS2.ipynb, requirements_styletts2.txt, update.py
A notebook demo ahead of UI implementation
=> StyleTTS2 Demo Notebook

README.md, react-ui/src/components/Header.tsx, react-ui/src/components/ResetButton.tsx, react-ui/src/components/TortoiseInput.tsx, react-ui/src/components/VallexInputs.tsx, react-ui/src/components/commonBorder.tsx, react-ui/src/data/parseFormChange.tsx, react-ui/src/data/split-and-recombine.ts, react-ui/src/functions/generateWithTortoise.tsx, react-ui/src/functions/generateWithVallex.tsx, react-ui/src/pages/api/gradio/[name].tsx, react-ui/src/pages/index.tsx, react-ui/src/pages/pipeline.tsx, react-ui/src/pages/rvc.tsx, react-ui/src/pages/vallex.tsx, react-ui/src/tabs/VallexParams.tsx, react-ui/src/types/HandleChange.tsx, server.py, src/rvc_tab/uvr5_tab.py, src/vall_e_x/vall_e_x_tab.py
=> Add Vall-E-X demo to React UI

README.md, react-ui/src/components/Header.tsx, server.py, src/Joutai.py, src/bark/generation_tab_bark.py, src/demucs/demucs_tab.py, src/demucs/demucs_tab_error.py, src/maha_tts/maha_tts_tab.py, src/mms/mms_tab.py, src/rvc_tab/rvc_tab.py, src/rvc_tab/rvc_tab_error.py, src/seamlessM4T/seamless_tab.py, src/stable_audio/stable_audio.py, src/styletts2/styletts2_tab.py, src/utils/suppress_warnings.py, src/vall_e_x/vall_e_x_tab.py
=> Stable audio updates

docker-compose.yml
Tried to do the docker install and wasn't working, the problem was in the ports on the dockerfile. Works fine for me now
=> Fix Dockerfile

tts_webui/utils/setup_or_recover.py
=> chore: update setup_or_recover.py

README.md, extensions.json, tools/extension_manager.py
=> Fix install/uninstall in extension manager

.gitignore, README.md, extensions.json, requirements.txt, server.py
Add kimi audio extension,
Add Kokoro TTS API extension definition (implementation not finished)
=> Add Kimi Audio

README.md, react-ui/package-lock.json, react-ui/package.json, react-ui/src/components/AceStepInputs.tsx, react-ui/src/components/AudioComponents.tsx, react-ui/src/components/Header.tsx, react-ui/src/components/PromptTextArea.tsx, react-ui/src/components/RouteCommands.tsx, react-ui/src/components/ui/accordion.tsx, react-ui/src/functions/generateWithAceStep.ts, react-ui/src/pages/api/gradio/[name].tsx, react-ui/src/pages/audio-music-generation.tsx, react-ui/src/pages/audio-music-generation/ace-step.tsx, react-ui/src/tabs/AceStepParams.ts, react-ui/tailwind.config.js, server.py, tts_webui/utils/list_dir_models.py
* Fix missing directory bug causing extensions to fail to load. Thanks Discord/Comstock for discovery of the bug.
* Add ACE-Step to React UI.
* Add emoji to Gradio UI categories for simplicity.
=> Add ACE-Step to React UI.

README.md, installer_scripts/init_app.js, installer_scripts/js/initializeApp.js, react-ui/src/pages/api/gradio/[name].tsx, server.py, tts_webui/utils/log_generation.py, tts_webui/utils/manage_model_state.py
=> Enhanced logger

README.md, react-ui/package-lock.json, react-ui/package.json, react-ui/src/components/AudioComponents.tsx, react-ui/src/components/ChatterboxInputs.tsx, react-ui/src/components/DownloadButton.tsx, react-ui/src/components/Header.tsx, react-ui/src/components/KokoroInputs.tsx, react-ui/src/components/MemoizedWaveSurferPlayer.tsx, react-ui/src/components/ProjectCard.tsx, react-ui/src/components/SeedInput.tsx, react-ui/src/components/ui/tabs.tsx, react-ui/src/components/ui/toast.tsx, react-ui/src/components/ui/toaster.tsx, react-ui/src/functions/generateWithChatterbox.ts, react-ui/src/functions/results/useSeedHelper.tsx, react-ui/src/hooks/use-toast.ts, react-ui/src/pages/api/gradio/[name].tsx, react-ui/src/pages/text-to-speech.tsx, react-ui/src/pages/text-to-speech/bark.tsx, react-ui/src/pages/text-to-speech/bark/generation.tsx, react-ui/src/pages/text-to-speech/chatterbox.tsx, react-ui/src/pages/tools/_api_config.tsx, react-ui/src/pages/tools/api_config.tsx, react-ui/src/tabs/BarkGenerationParams.tsx, react-ui/src/tabs/ChatterboxParams.ts, tts_webui/decorators/__init__.py, tts_webui/decorators/gradio_dict_decorator.py, tts_webui/utils/setup_or_recover.py
=> React UI UX boost

README.md, extensions.json, installer_scripts/root.ps1, react-ui/generate-plugin-imports.js, react-ui/src/components/MagnetModelSelector.tsx, react-ui/src/components/MemoizedWaveSurferPlayer.tsx, react-ui/src/components/MusicgenModelSelector.tsx, react-ui/src/hooks/useEffectOnce.tsx, react-ui/src/hooks/useLocalStorage.ts, react-ui/src/pages/pipeline.tsx, react-ui/src/pages/tools/_api_config.tsx, requirements.txt, tts_webui/config/config_utils.py
=> chatterbox and api upgrade, fix build warnings

README.md, documentation/manual_installation.md, notebooks/google_colab.ipynb, tools/extension_manager.py
https://www.youtube.com/watch?v=nLzaMfZl9Bo
and add extensions manager to google colab script:
https://www.youtube.com/watch?v=UlbOgxcz9Js
=> fix: add info about python 3.11 on google colab

README.md, extensions.json, react-ui/src/components/ChatterboxInputs.tsx, react-ui/src/pages/text-to-speech/chatterbox.tsx, react-ui/src/tabs/ChatterboxParams.ts
=> Chatterbox react UI

.gitignore, README.md, extensions.json
=> add FireRedTTS2

.gitignore, README.md, extensions.json
=> feat: add MegaTTS3 extension
